language: rust
matrix:
  include:
    - rust: nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - cargo test --release --verbose --all -- --ignored
  fast_finish: true
cache: cargo
