language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
        - cargo build --verbose --all
        - cargo test --verbose --all
        - cargo test --release --verbose --all -- --ignored
  fast_finish: true
cache: cargo
